
import java.util.Arrays;
import javax.xml.bind.DatatypeConverter;

public class TebakNama extends javax.swing.JFrame {

        String Nama;
        String generateNama;
        String Artis;

        public TebakNama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gambar = new javax.swing.JLabel();
        mulai = new javax.swing.JButton();
        Petunjuk = new javax.swing.JLabel();
        InputForUser = new javax.swing.JTextField();
        TombolSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Gambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\05_15_PERSONAJES_WEB_DORAEMON_BRUSH_BOING_DORAEMON.png")); // NOI18N

        mulai.setText("Mulai");
        mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiActionPerformed(evt);
            }
        });

        Petunjuk.setText("Klik Tombol Mulai ya!");
        Petunjuk.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PetunjukAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        TombolSubmit.setText("Submit");
        TombolSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gambar)
                    .addComponent(mulai)
                    .addComponent(TombolSubmit)
                    .addComponent(InputForUser, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Petunjuk, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Gambar)
                .addGap(18, 18, 18)
                .addComponent(mulai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Petunjuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputForUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TombolSubmit)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PetunjukAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PetunjukAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_PetunjukAncestorAdded

    private void mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiActionPerformed
        // TODO add your handling code here:
        String namaAsal = generateNama();
        Petunjuk.setText("Masukkan nama "+namaAsal);
    }
    private String generateNama() {
        String[] namaNama = {"Angeline","Demi Moore", "Dewi Sandra","Chelsea Islan", "Raisa", "Isyana", 
                             "Titik Puspa","Titik Sandora","ayam"};
        int index = 0;
        double generateNumber = Math.random() * 10;
        double nilaiIndex = Math.floor(generateNumber);
        index = (int) nilaiIndex;
        namaNama[index] = namaNama [index].toUpperCase();
        String namaSoal = namaNama[index];
        
        char[] namaAcak = namaNama[index].toCharArray();
        Arrays.sort(namaAcak);
        String random = new String(namaAcak);
        return random;
    }//GEN-LAST:event_mulaiActionPerformed

    private void TombolSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSubmitActionPerformed
        // TODO add your handling code here:
        String tebakanString = InputForUser.getText();
        
        if (tebakanString.equalsIgnoreCase(tebakanString)){
            Petunjuk.setText("luar biasa");
        } else {
            Petunjuk.setText("Kurang beruntung");
        }
    }//GEN-LAST:event_TombolSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakNama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gambar;
    private javax.swing.JTextField InputForUser;
    private javax.swing.JLabel Petunjuk;
    private javax.swing.JButton TombolSubmit;
    private javax.swing.JButton mulai;
    // End of variables declaration//GEN-END:variables
}
